objects/Beer__c.object
<CustomObject>
    <label>Beer</label>
    <nameField>
        <label>Beer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <label>External Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tagline__c</fullName>
        <label>Tagline</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

classes/BeerRESTCalloutTest.cls
@isTest
public class BeerRESTCalloutTest {
	
    @testSetup
    static void setup(){
        //Cargamos un record en Beer
        Beer__c beer = new Beer__c();
        beer.External_Id__c = 1;
        beer.Name = 'Test';
        beer.Tagline__c = 'Test Tagline';
        beer.Description__c = 'This is a description';
        insert beer;
    }
    
    @isTest
    static void testCalloutSuccess(){
        Test.setMock(HttpCalloutMock.class, new BeersMock());
        
        Test.startTest();
        BeerRESTCallout.getBeers();
        Test.stopTest();
        
        List<Beer__c> beers = [SELECT Name FROM Beer__c];
        System.assertEquals(2, beers.size());
    }
    
    @isTest
    static void testCalloutFailure(){
        Test.setMock(HttpCalloutMock.class, new BeersMockFailure());
        
        Test.startTest();
        BeerRESTCallout.getBeers();
        Test.stopTest();
        
        List<Beer__c> beers = [SELECT Name FROM Beer__c];
        System.assertEquals(1, beers.size());
    }
}