objects/Project__c.object
<CustomObject>
    <description>The projects.</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sprint__c.object
<CustomObject>
    <description>The sprints of a project.</description>
    <label>Sprint</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

objects/Work_Item__c.object
<CustomObject>
    <description>The work items of a sprint.</description>
    <label>Work Item</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Sprint__c</fullName>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipLabel>Work Items</relationshipLabel>
        <relationshipName>Work_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Done</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <inlineHelpText>Valid values (1, 2, 3, 5, 8 and 13).</inlineHelpText>
        <label>Story Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

classes/WorkItemController.cls
public class WorkItemController {
    /*Propiedad con getter y setter automáticos. Representa al estado del selecteList en la gui.
      Posibles valores: % (todos), Not Started, In Progress y Done.*/
    public String selectedValue { get; set; }
    
    //En el constructor, establecemos el valor inicial del valor seleccionado (selectList en el Visualforce).
    public WorkItemController(){selectedValue = '%';}
    
    public List<Work_Item__c> getItems(){
        //Obtenemos el id del work item (desde la url).
        String wiId = Apexpages.currentPage().getParameters().get('id');
        
        //Obtenemos su Story Point (que usaremos en la consulta final).
        List<Work_Item__c> story_point = [SELECT Story_Points__c FROM Work_Item__c WHERE Id = :wiId];
        
        //Obtenemos el id del proyecto a partir del id del sprint que se obtuvo en la segunda consulta (id work item).
        List<Sprint__c> projectid = [SELECT Project__c FROM Sprint__c 
                                     WHERE Id IN (SELECT Sprint__c FROM Work_Item__c WHERE Id = :wiId)];
        
        /*Consultamos los work items relacionados con los sprints obtenidos (ordenamos por nombre) y que no sea el mismo.
       	A partir de los sprints relacionados al proyecto consultado anteriormente.*/
        List<Work_Item__c> workItemsRelated = [SELECT Id, Name FROM Work_Item__c 
                                               WHERE Sprint__c IN (SELECT Id FROM Sprint__c 
                                                                   WHERE Project__c = :projectid[0].Project__c)
                                               AND (Id != :wiId) AND (Story_Points__c = :story_point[0].Story_Points__c)
                                               AND (Status__c LIKE :selectedValue+'%')
                                               ORDER BY Name];
        
        //Retornamos la lista
        return workItemsRelated;
    }
 
}